

image:
  repository: ubuntu
  pullPolicy: IfNotPresent
  tag: "24.04"

command:
  - "sleep"
  - "infinity"

replicaCount: 1
revisionHistoryLimit: 1

networkPolicy:
  enabled: false

# testing capabilities
securityContext:
  capabilities:
    drop: ["ALL"]
    add: ["SETUID", "SETGID", "CHOWN", "FOWNER", "DAC_OVERRIDE"]
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false 
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  seccompProfile:
    type: Unconfined

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi

startupProbe: {}
readinessProbe: {}
livenessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - "exit 0"

terminationGracePeriodSeconds: 2
