apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: sla-check
    namespace: httpbin-production
    files:
      - server.py
    options:
      disableNameSuffixHash: true

resources:
  - pod.yaml
